make safe_json_parse unsafe
jetruby/apollo_upload_server-ruby pull request #67
Opened 2024-04-30 22:09 UTC by cooperka

2024-04-30 22:14 UTC, cooperka commented
Edited to add context, fyi (GitHub posted this PR from their editor without a description)

2024-05-01 06:30 UTC, fuelen requested changes

2024-05-01 06:30 UTC, fuelen commented on lib/apollo_upload_server/graphql_data_builder.rb
> +      raise JSON::ParserError, "Malformed JSON in multipart form data"
This function is no longer safe, so let's remove it and use JSON.parse directly where needed.

2024-05-01 06:31 UTC, fuelen commented
I don't remember why it was done like this, so yes, let's try to remove safety :)

2024-05-15 20:48 UTC, cooperka commented
thanks for your patience -- feedback addressed and ready for re-review.

2024-05-16 21:01 UTC, cooperka commented on .gitignore
> +/vendor/bundle/
Common path for local gems to be stored

2024-05-16 21:02 UTC, cooperka commented on spec/apollo_upload_server/middleware_spec.rb
> +
Honestly not sure what changed here, tabs and line endings seem unaltered 🤷

2024-05-16 21:03 UTC, cooperka commented
Done! I basically just changed `foo` to `{}` so the JSON wouldn't fail.

2024-05-17 08:07 UTC, fuelen commented
Looks good. Thank you for the contribution!

2024-05-17 08:08 UTC, merged